import {
  type Project,
  type ProjectType,
  type ToolStackGroup,
  type Technology,
} from './types';

export const PROJECT_TYPES: readonly ProjectType[] = Object.freeze([
  {
    id: 'ai-development',
    label: 'AI Development',
    description: 'Automation and intelligence that supercharge workflows.',
  },
  {
    id: 'web-development',
    label: 'Web Development',
    description: 'Production-ready sites focused on performance and UX.',
  },
  {
    id: 'tooling',
    label: 'Tool Project',
    description: 'Utilities and developer tools that streamline everyday tasks.',
  },
  {
    id: 'software',
    label: 'Software',
    description: 'Standalone applications and product experiments.',
  },
  {
    id: 'minimal-app',
    label: 'Minimal App',
    description: 'Lightweight experiences engineered for focus and flow.',
  },
]);

export const TECHNOLOGIES: readonly Technology[] = Object.freeze([
  { id: 'react', label: 'React', category: 'frontend', icon: 'react' },
  { id: 'nextjs', label: 'Next.js', category: 'frontend', icon: 'nextjs' },
  { id: 'typescript', label: 'TypeScript', category: 'frontend', icon: 'typescript' },
  { id: 'tailwindcss', label: 'Tailwind CSS', category: 'frontend', icon: 'tailwindcss' },
  { id: 'html', label: 'HTML', category: 'frontend', icon: 'html' },
  { id: 'css', label: 'CSS', category: 'frontend', icon: 'css' },
  { id: 'javascript', label: 'JavaScript', category: 'frontend', icon: 'javascript' },
  { id: 'nodejs', label: 'Node.js', category: 'backend', icon: 'nodejs' },
  { id: 'fastapi', label: 'FastAPI', category: 'backend', icon: 'fastapi' },
  { id: 'python', label: 'Python', category: 'backend', icon: 'python' },
  { id: 'docker', label: 'Docker', category: 'backend', icon: 'docker' },
  { id: 'discordpy', label: 'discord.py', category: 'backend', icon: 'discordpy' },
  { id: 'cpp', label: 'C++', category: 'backend', icon: 'c++' },
  { id: 'postgresql', label: 'PostgreSQL', category: 'sql', icon: 'postgresql' },
  { id: 'supabase', label: 'Supabase', category: 'sql', icon: 'supabase' },
  { id: 'prisma', label: 'Prisma', category: 'sql', icon: 'prisma' },
  { id: 'vscode', label: 'VS Code', category: 'tooling', icon: 'vscode' },
  { id: 'vercel', label: 'Vercel', category: 'tooling', icon: 'vercel' },
  { id: 'figma', label: 'Figma', category: 'tooling', icon: 'figma' },
]);

export const TOOL_STACK_GROUPS: readonly ToolStackGroup[] = Object.freeze([
  {
    id: 'frontend',
    label: 'Front End',
    description: 'Where UI, interactions, and accessibility come together.',
    technologyIds: ['react', 'nextjs', 'tailwindcss', 'typescript', 'html', 'css', 'javascript'],
  },
  {
    id: 'backend',
    label: 'Back End',
    description: 'APIs, automation, and services that keep products running.',
    technologyIds: ['nodejs', 'fastapi', 'python', 'docker', 'discordpy', 'cpp'],
  },
  {
    id: 'sql',
    label: 'Data & SQL',
    description: 'Persistence options chosen for reliability and speed.',
    technologyIds: ['postgresql', 'supabase', 'prisma'],
  },
  {
    id: 'tooling',
    label: 'Apps & Tools',
    description: 'Daily drivers that shape the developer experience.',
    technologyIds: ['vscode', 'vercel', 'figma'],
  },
]);

export const PROJECTS: readonly Project[] = Object.freeze([
  {
    id: 'portfolio-website',
    title: 'Portfolio Website',
    excerpt: 'A tailored personal site that fuses motion, clarity, and personality.',
    date: 'Sep 2025',
    typeIds: ['web-development', 'minimal-app'],
    techIds: ['nextjs', 'react', 'tailwindcss', 'typescript'],
    link: 'https://sabicoder.xyz/',
    repo: 'https://github.com/NirussVn0/portfolio',
    image: '/projects/portfolio-website.svg',
    featured: true,
  },
  {
    id: 'pomodoro-peak',
    title: 'Pomodoro Peak',
    excerpt: 'A productivity companion built around the Pomodoro technique and delightful micro-interactions.',
    date: 'Sep 2025',
    typeIds: ['minimal-app', 'web-development'],
    techIds: ['nextjs', 'react', 'tailwindcss', 'typescript'],
    link: 'https://pp.sabicoder.xyz/',
    repo: 'https://github.com/NirussVn0/pomodoro-peak',
    image: '/projects/pomodoro-peak.svg',
    featured: true,
  },
  {
    id: 'linking-bio-homepage',
    title: 'Linking-Bio Homepage',
    excerpt:
      'The core web app for a customizable bio-link platform with personalization, analytics, and monetization hooks.',
    date: 'Jul 2025',
    typeIds: ['web-development', 'software'],
    techIds: ['nextjs', 'react', 'tailwindcss', 'typescript'],
    repo: 'https://github.com/NirussVn0/linking-bio-homepage',
    image: '/projects/linking-bio.svg',
  },
  {
    id: 'token-discord-checker',
    title: 'Token Discord Checker',
    excerpt: 'CLI-first tool for auditing Discord tokens safely with real-time insights.',
    date: 'Jun 2025',
    typeIds: ['tooling'],
    techIds: ['nodejs', 'typescript'],
    repo: 'https://github.com/NirussVn0/token-discord-checker',
    image: '/projects/discord-token.svg',
  },
  {
    id: 'gmail-automation-tool',
    title: 'Gmail Automation Tool',
    excerpt: 'Automates Gmail sequences with FastAPI, robust scheduling, and Dockerized deployment.',
    date: 'Jun 2025',
    typeIds: ['ai-development', 'tooling'],
    techIds: ['python', 'fastapi', 'docker'],
    repo: 'https://github.com/NirussVn0/Gmail-Automation-Tool',
    image: '/projects/gmail-automation.svg',
    featured: true,
  },
  {
    id: 'selfbot',
    title: 'SelfBot',
    excerpt: 'Discord self-bot built with pythonic ergonomics and modular commands.',
    date: 'Apr 2025',
    typeIds: ['tooling'],
    techIds: ['python', 'discordpy'],
    repo: 'https://github.com/NirussVn0/Python-Hikari-SelfBot',
    image: '/projects/selfbot.svg',
  },
  {
    id: 'thptqg-countdown-ex',
    title: 'THPTQG Countdown EX',
    excerpt: 'A live countdown experience for Vietnam’s high school graduation exam.',
    date: 'Apr 2025',
    typeIds: ['minimal-app', 'web-development'],
    techIds: ['nextjs', 'react', 'tailwindcss', 'typescript'],
    link: 'https://project.sabicoder.xyz/',
    repo: 'https://github.com/NirussVn0/thptqg-countdown',
    image: '/projects/thptqg-countdown.svg',
  },
  {
    id: 'animated-404',
    title: 'Animated 404 Page',
    excerpt: 'A minimal yet playful 404 experience showcasing motion design with vanilla web tech.',
    date: 'Feb 2025',
    typeIds: ['web-development', 'minimal-app'],
    techIds: ['html', 'css', 'javascript'],
    repo: 'https://github.com/NirussVn0/404-animation',
    image: '/projects/animated-404.svg',
  },
]);
